version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $${TYPEORM_PASSWORD}
      MYSQL_DATABASE: $${TYPEORM_DATABASE}
      MYSQL_USER: $${TYPEORM_USERNAME}
      MYSQL_PASSWORD: $${TYPEORM_PASSWORD}
    networks:
      - backnet
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=password 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }

  backend:
    image: pokeapi
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - /app/node_modules
    environment:
      NODE_ENV: $${NODE_ENV}
      PORT: $${PORT}
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: $${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: $${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: $${TYPEORM_DATABASE}
      TYPEORM_PORT: $${TYPEORM_PORT}
      TYPEORM_LOGGING: 1
      TYPEORM_ENTITIES: $${TYPEORM_ENTITIES}
      TYPEORM_SYNCHRONIZE: 1
    depends_on:
      - mysql
    networks:
      - backnet

networks:
  backnet:
    driver: bridge



